### PR TITLE
Added a flag for forced person creation

### PR DESCRIPTION
**Pull request by naitsirch**
The `force` flag has to be set to true, if there is already another person with the same name (yes, in churches with a larger number of members it may happen that there are different persons with the same name ;-)) and the person should be created anyways. Otherwise the API responds with an error.

### CODE REVIEW

**Comment by DumbergerL** [comment]
@naitsirch That is a important point! 

Can you add the flag in the example code for the docs and also describe the purpose in the docs?
https://github.com/5pm-HDH/churchtools-api/blob/114d4db147bade092de32bdde63cc2c0a57c0ce6/tests/unit/Docs/PersonRequestTest.php#L48

**Comment by naitsirch** [comment]
I'll lookbinto it ;-)

**Comment by naitsirch** [comment]
Done. I hope I have done it correctly ^^

**Comment by naitsirch** [comment]
Thank you for your trust to let me commit to your repository. I am not sure whether I'll do that, because it is your project and my coding style differs from yours. So I'll prefer to create PRs and wait for your response, if this is okay for you.

Btw. there won't be many more PRs from me, because the feature set, that I need is mostly complete. The only thing I still need, is the possibility to synchronize person photos. If this works, I'll stop annoying you :-D

**Comment by DumbergerL** [comment]
Feel free to contribute however you like! I am grateful for your support!

Your update for the doc looks great! 
I had to adjust the logic for creating new models because of the Absence API. Here the approach with the setters didn't work, because the Absence-Model expected an AbsenceReason-Model as property. Maybe you can take a look at the code again and check if this works for you?

https://github.com/5pm-HDH/churchtools-api/blob/4c50a1b9ac2afc28fe115a2252b583aa0a662908/src/Requests/AbstractRequestBuilder.php#L87-L96

**Comment by DumbergerL** [comment]
I would be happy if we stay in contact. If you want you can send me an email to: lukas.dumberger@gmail.com

I would be very interested in what use-case you are using the ChruchTools API for at your church. Maybe we can exchange ideas sometime! I am always interested in new project ideas.

**Comment by DumbergerL** [comment]
Hi @naitsirch,
can you approve i my changes for the code-base works for you? 

> Your update for the doc looks great! I had to adjust the logic for creating new models because of the Absence API. Here the approach with the setters didn't work, because the Absence-Model expected an AbsenceReason-Model as property. Maybe you can take a look at the code again and check if this works for you?
> 
> https://github.com/5pm-HDH/churchtools-api/blob/4c50a1b9ac2afc28fe115a2252b583aa0a662908/src/Requests/AbstractRequestBuilder.php#L87-L96

**Comment by naitsirch** [comment]
Sorry, I did not had the time, to check it, yet. But if it works for you, you can merge it and if I'll experience any errors I'd fix it vor create an issue ;-)

Otherwise I plan to go in with it at the weekend.

**Comment by DumbergerL** [comment]
Thanks for your reply. I close the PR. 

By the way: You said you would need to upload avatar of persons? I added the file-api today. I hope this helps you: https://github.com/5pm-HDH/churchtools-api/pull/114

**Comment by naitsirch** [comment]
I have tested it now, and it works fine ;-)
Thanks for working on the file API. I'll try to test it at the weekend and give you feedback.

**Comment by naitsirch** [comment]
By the way, here is the project where I am using your library: https://github.com/naitsirch/ecgpb-memberlist.

This is the interactive command that I use to run the synchronization process:
https://github.com/naitsirch/ecgpb-memberlist/blob/master/src/Command/ChurchtoolsSyncInteractiveCommand.php

And this is the service class, that is responsible for the business logic:
https://github.com/naitsirch/ecgpb-memberlist/blob/master/src/Service/ChurchTools/Synchronizer.php

I'll contact you per mail for more details ;-)

**Pull request merged**
