### PR TITLE
Moved group type classes to separate namespace

### PR DESCRIPTION
**Pull request by stollr**
I would like to move the group type classes to a separate namespace, because I think it is more consistent to place the group type classes to their own namespace like other models.

What do you think?

### CODE REVIEW

**Comment by DumbergerL** [comment]
@stollr Basically, I think it's a great suggestion. However, I'm a bit afraid to merge it because it's a breaking change. I would like to try to keep the project as stable as possible with version 2. There are enough breaking changes in the ChurchTools API, so I want to at least try to cushion this a little with the project here.

I would take the change into account when switching to a new major version.

**Comment by stollr** [comment]
But there was no release since the addition of the group type, so I think this would not be regarded as a BC break.

**Comment by DumbergerL** [comment]
You are absolutely right. Sorry. I did not realise that this feature had not yet been shipped. Thank you very much!

**Comment by stollr** [comment]
You're welcome 🙂

**Pull request merged**
