### PR TITLE
Added method to update person data

### PR DESCRIPTION
**Pull request by naitsirch**
Currently there is no way to update a person's data with this adapter. This PR adds a new `update` method to the `PersonRequest`and `PersonRequestBuilder` classes.

This PR also contains user documentation and unit tests.

This is how the method can be used:
```php
$person = PersonRequest::findOrFail(21);
$person->setEmail('new-mail@example.com');

PersonRequest::update($person);
```
In the doc you'll find some more explanations.

I'll be happy to see this getting merged, soon :-)

### CODE REVIEW

**Comment by naitsirch** [comment]
@DumbergerL I am not sure what to with the failed Doc-Generator check "Inconsistent Docs. Please run DocGenerator and check in changed Files.".

I suspect that the added code blocks in the `docs/PersonAPI.md` file are the reason. But how can I chaeck that?

When I run `omposer run-script docs-generator` there are no errors.

**Comment by DumbergerL** [comment]
@naitsirch Thank's for your contribution. I have thought of this "writing to api"-topic quite a lot. But i think it's not that big thing because ChurchTools don't offer many PATCH-Routes. So i think your approach is great!

We should consider to add some Code-Checks to validate if all MODIFIABLE_ATTRIBUTES are contained in the Model-Class. This could also include to check if all Model-Attributes have Setters and Getter.

**Comment by naitsirch** [comment]
Can you explain your last paragraph a little bit more?
If not all MODIFIABLE_ATTRIBUTES are contained in the model class it won't have any negative effect.

**Comment by DumbergerL** [comment]
Yes you are right! If the modifiableAttributes contains a key that does not exists in the Class it won't be exposed to the REST-API. I wrote a Unit-Test for this case: https://github.com/5pm-HDH/churchtools-api/pull/84/commits/73db4f4024e1c21555b9e480488b7e91edec7ab6

**Comment by DumbergerL** [comment]
@naitsirch I refactored your implementation a little bit. Can you check if it still faces your needs? Does it work for you this way? If yes i would merge the PR.

**Comment by naitsirch** [comment]
I hope I'll have time in the next days. Then I will test it and give feedback.

**Comment by naitsirch** [comment]
@DumbergerL I have tested it now and it works fine :-)

**Pull request merged**
